# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

      ## create application-dev.yaml
    - name: make application-dev.yaml
      run: |
        ## create application-dev.yaml
        cd ./src/main/resources

        touch ./application-dev.yaml
        
        echo "${{ secrets.DATABASE }}" >> ./application-dev.yaml
        shell: bash  

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/talken .
        docker push ${{ secrets.DOCKER_REPO }}/talken

      ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_REPO }}/talken
          sudo docker pull ${{ secrets.DOCKER_REPO }}/talken-nginx
          docker-compose up -d
          docker image prune -f
